services:
  - type: web
    name: sentimentai-2050
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /status
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
